"""update_report_table

Revision ID: 0421d380f000
Revises: 28a9e44a4558
Create Date: 2026-06-27 14:20:06.967788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0421d380f000'
down_revision: Union[str, Sequence[str], None] = '28a9e44a4558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('title', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('report', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('critic_score', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('critic_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('clarification_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('clarification_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('status', sa.String(), nullable=False))
    op.add_column('reports', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('reports', 'sources',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('reports', 'report_md')
    op.drop_column('reports', 'url_count')
    op.drop_column('reports', 'sub_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('sub_questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('url_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('report_md', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('reports', 'sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('reports', 'updated_at')
    op.drop_column('reports', 'meta')
    op.drop_column('reports', 'status')
    op.drop_column('reports', 'clarification_answers')
    op.drop_column('reports', 'clarification_questions')
    op.drop_column('reports', 'critic_feedback')
    op.drop_column('reports', 'critic_score')
    op.drop_column('reports', 'report')
    op.drop_column('reports', 'title')
    # ### end Alembic commands ###
