"""Initial schema

Revision ID: 771ebdd0fa3b
Revises: 
Create Date: 2026-06-27 03:06:12.266047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771ebdd0fa3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('report_md', sa.String(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('sub_questions', sa.JSON(), nullable=False),
    sa.Column('url_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
